mysite/fortune/urls.py
from django.conf.urls import url

from . import views

app_name = 'fortune'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new/$', views.FortuneCreate.as_view(), name='new'),
    url(r'^results/$', views.TopView.as_view(), name='results'),
    url(r'^(?P<fortune_id>[0-9]+)/up/$', views.up, name='up'),
    url(r'^(?P<fortune_id>[0-9]+)/down/$', views.down, name='down'),
    url(r'^connect/$', views.connect, name='connect'),
    url(r'^deconnect/$', views.deconnect, name='deconnect'),
    url(r'^register/$', views.register, name='register'),
    url(r'^list/$', views.UserFortuneView.as_view(), name='myFortunes')
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^fortune/', include('fortune.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/fortune/models.py
import datetime

from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.models import User

class Fortune(models.Model):
    user = models.ForeignKey(User, blank=True, null=True)
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=1000)
    pub_date = models.DateTimeField(default = datetime.now)
    score = models.IntegerField(default=0)
    def __str__(self):
        return self.title

mysite/fortune/forms.py
from django import forms
from .models import Fortune

class FortuneForm(forms.ModelForm):
    class Meta:
        model = Fortune
        fields = ['title','text']

class ConnexionForm(forms.Form):
    username = forms.CharField(label="User name", max_length=30)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

mysite/fortune/views.py
from django.http import HttpResponse
from django.views import generic
from django.utils import timezone
from datetime import datetime
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from .forms import FortuneForm, ConnexionForm
from .models import Fortune

class IndexView(generic.ListView):
    template_name = 'fortune/index.html'
    context_object_name = 'latest_fortune_list'

    def get_queryset(self):
        return Fortune.objects.order_by('-pub_date')

class TopView(generic.ListView):
    template_name = 'fortune/results.html'
    context_object_name = 'latest_fortune_list'

    def get_queryset(self):
        return Fortune.objects.order_by('-score')[:30]

class DetailView(generic.DetailView):
    model = Fortune
    template_name = 'fortune/detail.html'

class UserFortuneView(generic.ListView):
    template_name = 'fortune/list.html'
    context_object_name = 'list'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Fortune.objects.filter(user=self.request.user).order_by('-pub_date')
        else:
            return

class FortuneCreate(generic.FormView):
    model = Fortune
    form_class = FortuneForm
    success_url = '/fortune/'
    template_name = 'fortune/new.html'
    def form_valid(self, form):
        self.object = form.save(commit=True)
        if self.request.user.is_authenticated:
            self.object.user = self.request.user
        self.object.score = 0
        self.object.pub_date = datetime.now()
        self.object.save()
        return super(FortuneCreate, self).form_valid(form)

def up(request, fortune_id):
    fortune = get_object_or_404(Fortune, pk=fortune_id)
    fortune.score += 1
    if request.user.is_authenticated:
        fortune.score += 1
    fortune.save()
    return HttpResponseRedirect(reverse('fortune:detail', args=(fortune.id,)))

def down(request, fortune_id):
    fortune = get_object_or_404(Fortune, pk=fortune_id)
    fortune.score -= 1
    if request.user.is_authenticated:
        fortune.score -= 1
    fortune.save()
    return HttpResponseRedirect(reverse('fortune:detail', args=(fortune.id,)))

def connect(request):
    error = False

    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
            else:
                error = True
    else:
        form = ConnexionForm()

    return render(request, 'fortune/login.html', locals())

def deconnect(request):
    logout(request)
    return HttpResponseRedirect(reverse('fortune:connect'))

def register(request):
    error = False

    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = User.objects.create_user(username, username,password)
            if user:
                login(request, user)
            else:
                error = True
    else:
        form = ConnexionForm()
    return render(request, 'fortune/register.html', locals())

mysite/fortune/templates/fortune/detail.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<h1>{{fortune.title}}</h1>

<nav class="navbar navbar-default">
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li><a href="{% url 'fortune:index' %}">Menu</a></li>
			<li><a href="{% url 'fortune:new' %}">Create a new fortune</a></li>
			<li><a href="{% url 'fortune:results' %}">Top 30</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url 'fortune:deconnect' %}">Log out</a></li>
			<li><a href="{% url 'fortune:myFortunes' %}">My Fortunes</a></li>
			{% else %}
			<li><a href="{% url 'fortune:connect' %}">Log in</a></li>
			{% endif %}
		</ul>
	</div>
</nav>

<table>
	</tr>
	<td>
<form action="{% url 'fortune:up' fortune.id %}" method="post">
	{% csrf_token %}
	{% buttons %}
	<button type="submit" class="btn btn-success">+</button>
	{% endbuttons %}
</form>
	</td>
		<td><p style="padding-left:5px; padding-right:5px;">Score: {{ fortune.score }}</p></td>
	<td>
<form action="{% url 'fortune:down' fortune.id %}" method="post">
	{% csrf_token %}
	{% buttons %}
	<button type="submit" class="btn btn-danger">-</button>
	{% endbuttons %}
</form>
	</td>
	</tr>
</table>

<div class="jumbotron">
	<div class="col-lg-offset-1">
    <p>{{fortune.text}}</p>
	</div>
</div>
<li>{{fortune.pub_date}}</li>

mysite/fortune/templates/fortune/index.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<div>
<h1>Fortune</h1>
<nav class="navbar navbar-default">
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li class="active"><a href="{% url 'fortune:index' %}">Menu</a></li>
			<li><a href="{% url 'fortune:new' %}">Create a new fortune</a></li>
			<li><a href="{% url 'fortune:results' %}">Top 30</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url 'fortune:deconnect' %}">Log out</a></li>
			<li><a href="{% url 'fortune:myFortunes' %}">My Fortunes</a></li>
			{% else %}
			<li><a href="{% url 'fortune:connect' %}">Log in</a></li>
			{% endif %}
		</ul>
	</div>
</nav>
</div>
<div>
{% if latest_fortune_list %}
	<ul>
    {% for fortune in latest_fortune_list %}
        <h2><li><a href="{% url 'fortune:detail' fortune.id %}">{{ fortune.title }}</a></li></h2>
	<div class="jumbotron">
	<div class="col-lg-offset-1">
		<p>{{ fortune.text }}</p>
	</div>
	</div>
    {% endfor %}
    </ul>
{% else %}
    <p>No Fortune are available.</p>
{% endif %}
</div>

mysite/fortune/templates/fortune/list.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<div>
<h1>Fortune</h1>
<nav class="navbar navbar-default">
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li><a href="{% url 'fortune:index' %}">Menu</a></li>
			<li><a href="{% url 'fortune:new' %}">Create a new fortune</a></li>
			<li><a href="{% url 'fortune:results' %}">Top 30</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url 'fortune:deconnect' %}">Log out</a></li>
			<li class="active"><a href="{% url 'fortune:myFortunes' %}">My Fortunes</a></li>
			{% else %}
			<li><a href="{% url 'fortune:connect' %}">Log in</a></li>
			{% endif %}
		</ul>
	</div>
</nav>
</div>
<div>
{% if list %}
	<ul>
    {% for fortune in list %}
        <h2><li><a href="{% url 'fortune:detail' fortune.id %}">{{ fortune.title }}</a></li></h2>
	<div class="jumbotron">
	<div class="col-lg-offset-1">
		<p>{{ fortune.text }}</p>
	</div>
	</div>
    {% endfor %}
    </ul>
{% else %}
    <p>No Fortune are available.</p>
{% endif %}
</div>

mysite/fortune/templates/fortune/login.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<h1>Log In</h1>
<nav class="navbar navbar-default">
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li><a href="{% url 'fortune:index' %}">Menu</a></li>
			<li><a href="{% url 'fortune:new' %}">Create a new fortune</a></li>
			<li><a href="{% url 'fortune:results' %}">Top 30</a></li>
			{% if user.is_authenticated %}
			<li class="active"><a href="{% url 'fortune:deconnect' %}">Log out</a></li>
			<li><a href="{% url 'fortune:myFortunes' %}">My Fortunes</a></li>
			{% else %}
			<li class="active"><a href="{% url 'fortune:connect' %}">Log in</a></li>
			{% endif %}
			</ul>
	</div>
</nav>

{% if error %}
<p><strong>Utilisateur inconnu ou mauvais de mot de passe.</strong></p>
{% endif %}

{% if user.is_authenticated %}
<h2>You are connected, {{ user.username }} !</h2>
<button><a href="{% url 'fortune:deconnect' %}">Log out</a></button>
{% else %}
<form method="post" action=".">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Login" />
</form>
<button><a href="{% url 'fortune:register' %}">Register</a></button>
{% endif %}

mysite/fortune/templates/fortune/new.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<h1>Create your fortune</h1>
<nav class="navbar navbar-default">
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li><a href="{% url 'fortune:index' %}">Menu</a></li>
			<li class="active"><a href="{% url 'fortune:new' %}">Create a new fortune</a></li>
			<li><a href="{% url 'fortune:results' %}">Top 30</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url 'fortune:deconnect' %}">Log out</a></li>
			<li><a href="{% url 'fortune:myFortunes' %}">My Fortunes</a></li>
			{% else %}
			<li><a href="{% url 'fortune:connect' %}">Log in</a></li>
			{% endif %}
		</ul>
	</div>
</nav>
<form action="" method=post>
	{% csrf_token %}
	{% bootstrap_form form %}
	<p><input type="submit" value="Save"></p>
</form>

mysite/fortune/templates/fortune/register.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<h1>Register</h1>
<nav class="navbar navbar-default">
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li><a href="{% url 'fortune:index' %}">Menu</a></li>
			<li><a href="{% url 'fortune:new' %}">Create a new fortune</a></li>
			<li><a href="{% url 'fortune:results' %}">Top 30</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url 'fortune:deconnect' %}">Log out</a></li>
			<li><a href="{% url 'fortune:myFortunes' %}">My Fortunes</a></li>
			{% else %}
			<li><a href="{% url 'fortune:connect' %}">Log in</a></li>
			{% endif %}
		</ul>
	</div>
</nav>
{% if user.is_authenticated %}
<h2>You are connected, {{ user.username }} !</h2>
<button><a href="{% url 'fortune:deconnect' %}">Log out</a></button>
{% else %}
<form action="" method=post>
	{% csrf_token %}
	{% bootstrap_form form %}
	<p><input type="submit" value="Save"></p>
</form>
{% endif %}

mysite/fortune/templates/fortune/results.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<h1>Top 30 Fortune</h1>
<nav class="navbar navbar-default">
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li><a href="{% url 'fortune:index' %}">Menu</a></li>
			<li><a href="{% url 'fortune:new' %}">Create a new fortune</a></li>
			<li class="active"><a href="{% url 'fortune:results' %}">Top 30</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url 'fortune:deconnect' %}">Log out</a></li>
			<li><a href="{% url 'fortune:myFortunes' %}">My Fortunes</a></li>
			{% else %}
			<li><a href="{% url 'fortune:connect' %}">Log in</a></li>
			{% endif %}
		</ul>
	</div>
</nav>
{% if latest_fortune_list %}
    <ul>
    {% for fortune in latest_fortune_list %}
        <h3>Score: {{fortune.score}}</h3>
		<div class="jumbotron">
		<div class="col-lg-offset-1">
		<h2><li><a href="{% url 'fortune:detail' fortune.id %}">{{ fortune.title }}</a></li></h2>
		</div>
		</div>
    {% endfor %}
    </ul>
{% else %}
    <p>No Fortune are available.</p>
{% endif %}